import { useState } from 'react'
import Icon from '../../components/Icon.jsx'
import './Checkout.css'

const money = (amount) => `$${amount.toFixed(2)}`
const paymentLabels = { card: 'Credit or debit card', crypto: 'Cryptocurrency', giftcard: 'Gift card' }

export default function Checkout({ cart, customer, onCustomer, onQuantity, onRemove, onBack, onPlaceOrder, receipt }) {
  const [deliveryMode, setDeliveryMode] = useState('surprise')
  const [paymentMethod, setPaymentMethod] = useState('card')
  const showFallback = (event) => { event.currentTarget.onerror = null; event.currentTarget.src = '/product-fallback.svg' }
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const shipping = subtotal === 0 || subtotal >= 75 ? 0 : 6.95
  const total = subtotal + shipping

  if (receipt) return <section className="checkout-page"><article className="receipt-sheet"><div className="receipt-topline"><div className="receipt-brand"><span className="receipt-brand-mark">w</span><span>warmgesture<span>.</span></span></div><span className="receipt-status"><Icon name="check" size={13}/> Order recorded</span></div><div className="receipt-heading"><span className="eyebrow">A LITTLE JOY IS ON ITS WAY</span><h1>Thanks for<br/><em>sending love.</em></h1><p>Your order details are saved in this browser.</p></div><div className="receipt-code"><div><small>ORDER CONFIRMATION</small><strong>{receipt.code}</strong></div><div><small>ORDER DATE</small><strong>{new Date(receipt.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</strong></div></div><div className="receipt-section"><h2>Order details</h2>{receipt.items.map((item) => <div className="receipt-item" key={item.id}><span>{item.name} <small>× {item.quantity}</small></span><strong>{money(item.price * item.quantity)}</strong></div>)}<div className="receipt-item"><span>Delivery</span><strong>{receipt.shipping === 0 ? 'Free' : money(receipt.shipping)}</strong></div><div className="receipt-total"><span>Total</span><strong>{money(receipt.total)}</strong></div></div><div className="receipt-two-col"><div className="receipt-section"><h2>Delivery</h2><p><strong>{receipt.deliveryMode === 'surprise' ? 'Surprise gift' : 'Standard delivery'}</strong><br/>{receipt.customer.recipientName}<br/>{receipt.deliveryMode === 'surprise' ? <>Address to be arranged by WarmGesture<br/></> : <>{receipt.customer.address}<br/>{receipt.customer.city}, {receipt.customer.postal}<br/></>}{receipt.customer.recipientPhone}<br/>From: {receipt.customer.anonymous ? 'Hidden sender' : receipt.customer.senderName || 'Sender not provided'}</p></div><div className="receipt-section"><h2>Payment selection</h2><p><strong>{paymentLabels[receipt.paymentMethod]}</strong><br/>Payment not processed</p></div></div>{receipt.customer.note && <div className="receipt-section receipt-note"><h2>Gift note</h2><p>“{receipt.customer.note}”</p></div>}<div className="receipt-disclaimer">This is a local order receipt. No payment was taken and no order was sent to a fulfillment system.</div><div className="receipt-actions"><button className="button-primary" onClick={() => window.print()}>Print receipt <span><Icon name="arrowRight" size={14}/></span></button><button className="receipt-back" onClick={onBack}>Continue shopping</button></div></article></section>

  return <section className="checkout-page"><div className="checkout-heading"><button className="checkout-back" onClick={onBack}><Icon name="arrowLeft" size={14}/> Continue shopping</button><span className="eyebrow">YOUR LITTLE LOVE DELIVERY</span><h1>Shopping <em>bag.</em></h1></div>
    <div className="checkout-layout"><div className="checkout-main">
      <div className="checkout-panel"><div className="panel-title"><h2>Your gifts</h2><span>{cart.reduce((sum, item) => sum + item.quantity, 0)} items</span></div>
        {cart.length ? <div className="cart-items">{cart.map((item) => <article className="cart-item" key={item.id}><img src={item.imageUrl} alt={item.name} onError={showFallback}/><div className="cart-item-info"><h3>{item.name}</h3><p>{item.note}</p><strong>{money(item.price)}</strong><div className="quantity-control"><button onClick={() => onQuantity(item.id, -1)} aria-label={`Remove one ${item.name}`}><Icon name="minus" size={13}/></button><span>{item.quantity}</span><button onClick={() => onQuantity(item.id, 1)} aria-label={`Add one ${item.name}`}><Icon name="plus" size={13}/></button></div></div><button className="remove-item" onClick={() => onRemove(item.id)}>Remove</button></article>)}</div> : <div className="empty-cart"><Icon name="gift" size={38}/><p>Your bag is waiting for something lovely.</p><button className="text-link" onClick={onBack}>Find a gift <Icon name="arrowRight" size={14}/></button></div>}
      </div>
      <form className="checkout-panel customer-form" onSubmit={(event) => { event.preventDefault(); onPlaceOrder({ deliveryMode, paymentMethod }) }}>
        <section className="checkout-form-section"><div className="panel-title"><div><span className="step-label">STEP 01</span><h2>How should we send it?</h2></div></div><div className="delivery-mode-options">
          <label className={deliveryMode === 'surprise' ? 'mode-card mode-selected' : 'mode-card'}><input type="radio" name="delivery-mode" value="surprise" checked={deliveryMode === 'surprise'} onChange={() => setDeliveryMode('surprise')}/><span className="mode-icon"><Icon name="gift" size={21}/></span><span className="mode-copy"><strong>Surprise gift</strong><small>We’ll call the recipient to coordinate delivery. Their address is not needed here.</small></span><span className="mode-radio"/></label>
          <label className={deliveryMode === 'standard' ? 'mode-card mode-selected' : 'mode-card'}><input type="radio" name="delivery-mode" value="standard" checked={deliveryMode === 'standard'} onChange={() => setDeliveryMode('standard')}/><span className="mode-icon"><Icon name="home" size={21}/></span><span className="mode-copy"><strong>Standard delivery</strong><small>Enter their delivery address and we’ll send the gift there.</small></span><span className="mode-radio"/></label>
        </div>{deliveryMode === 'surprise' && <label className="anonymous-option"><input type="checkbox" checked={Boolean(customer.anonymous)} onChange={(event) => onCustomer('anonymous', event.target.checked)}/> Keep my name hidden from the recipient</label>}</section>
        <section className="checkout-form-section"><div className="panel-title"><div><span className="step-label">STEP 02</span><h2>Recipient information</h2></div><span>Who should receive the gift?</span></div><div className="form-grid"><label>Recipient’s name<input required autoComplete="name" value={customer.recipientName ?? ''} onChange={(e) => onCustomer('recipientName', e.target.value)} placeholder="Their full name"/></label><label>Recipient’s phone<input type="tel" required autoComplete="tel" value={customer.recipientPhone ?? ''} onChange={(e) => onCustomer('recipientPhone', e.target.value)} placeholder="For delivery coordination"/></label>{deliveryMode === 'standard' && <><label className="wide-field">Delivery address<input required autoComplete="street-address" value={customer.address ?? ''} onChange={(e) => onCustomer('address', e.target.value)} placeholder="Street and number"/></label><label>City<input required autoComplete="address-level2" value={customer.city ?? ''} onChange={(e) => onCustomer('city', e.target.value)} placeholder="City"/></label><label>ZIP / postal code<input required autoComplete="postal-code" value={customer.postal ?? ''} onChange={(e) => onCustomer('postal', e.target.value)} placeholder="ZIP code"/></label></>}{deliveryMode === 'surprise' && <p className="surprise-coordination wide-field"><Icon name="check" size={15}/> WarmGesture will contact the recipient to arrange delivery details.</p>}<label>Your name<input autoComplete="name" value={customer.senderName ?? ''} onChange={(e) => onCustomer('senderName', e.target.value)} placeholder="Optional"/></label><label>Email for your receipt<input type="email" required autoComplete="email" value={customer.email ?? ''} onChange={(e) => onCustomer('email', e.target.value)} placeholder="you@example.com"/></label><label className="wide-field">Gift note <span className="optional-label">Optional</span><textarea value={customer.note ?? ''} onChange={(e) => onCustomer('note', e.target.value)} placeholder="Write a little something from you…" rows="3"/></label></div></section>
        <section className="checkout-form-section"><div className="panel-title"><div><span className="step-label">STEP 03</span><h2>Choose a payment method</h2></div></div><div className="payment-options">
          <label className={paymentMethod === 'card' ? 'payment-card payment-selected' : 'payment-card'}><input type="radio" name="payment-method" value="card" checked={paymentMethod === 'card'} onChange={() => setPaymentMethod('card')}/><Icon name="card" size={21}/><span><strong>Card</strong><small>Credit or debit</small></span></label>
          <label className={paymentMethod === 'crypto' ? 'payment-card payment-selected' : 'payment-card'}><input type="radio" name="payment-method" value="crypto" checked={paymentMethod === 'crypto'} onChange={() => setPaymentMethod('crypto')}/><Icon name="coin" size={21}/><span><strong>Crypto</strong><small>Cryptocurrency</small></span></label>
          <label className={paymentMethod === 'giftcard' ? 'payment-card payment-selected' : 'payment-card'}><input type="radio" name="payment-method" value="giftcard" checked={paymentMethod === 'giftcard'} onChange={() => setPaymentMethod('giftcard')}/><Icon name="giftCard" size={21}/><span><strong>Gift card</strong><small>Store gift card</small></span></label>
        </div><p className="payment-note">Payment options are saved with your local order. Secure payment processing is not connected yet, so no card or crypto payment will be collected.</p></section>
        <p className="privacy-note">Your checkout information is saved in this browser for this local shopping experience.</p>
      </form>
    </div><aside className="order-summary"><span className="eyebrow">THE LITTLE DETAILS</span><h2>Order summary</h2><div className="summary-row"><span>Gifts subtotal</span><span>{money(subtotal)}</span></div><div className="summary-row"><span>Delivery</span><span>{shipping === 0 ? 'On us' : money(shipping)}</span></div>{subtotal > 0 && subtotal < 75 && <p className="shipping-hint">You’re ${(75 - subtotal).toFixed(2)} away from free delivery.</p>}<div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div><button className="place-order" disabled={!cart.length} onClick={() => document.querySelector('.customer-form')?.requestSubmit()}>Create order & receipt <span><Icon name="arrowRight" size={15}/></span></button><p className="checkout-disclaimer">Order saved locally · No payment is processed</p><div className="summary-foot"><Icon name="heart" size={13}/> &nbsp; Packed with care, always</div></aside></div>
  </section>
}
