import './Checkout.css'

const money = (amount) => `$${amount.toFixed(2)}`

export default function Checkout({ cart, customer, onCustomer, onQuantity, onRemove, onBack, onPlaceOrder, orderCode }) {
  const showFallback = (event) => { event.currentTarget.onerror = null; event.currentTarget.src = '/product-fallback.svg' }
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const shipping = subtotal === 0 || subtotal >= 75 ? 0 : 6.95
  const total = subtotal + shipping

  if (orderCode) return <section className="checkout-page"><div className="order-success"><span className="success-heart">♡</span><span className="eyebrow">A LITTLE JOY IS ON ITS WAY</span><h1>Thank you for<br/><em>sending love.</em></h1><p>Your order has been saved in this browser.</p><div className="order-code"><small>YOUR SHOPPING ORDER CODE</small><strong>{orderCode}</strong></div><p className="order-local-note">Keep this code for your records. This local checkout does not send payment or order details to the store.</p><button className="button-primary" onClick={onBack}>Back to shopping <span>↗</span></button></div></section>

  return <section className="checkout-page"><div className="checkout-heading"><button className="checkout-back" onClick={onBack}>← Continue shopping</button><span className="eyebrow">YOUR LITTLE LOVE DELIVERY</span><h1>Shopping <em>bag.</em></h1></div>
    <div className="checkout-layout"><div className="checkout-main">
      <div className="checkout-panel"><div className="panel-title"><h2>Your gifts</h2><span>{cart.reduce((sum, item) => sum + item.quantity, 0)} items</span></div>
        {cart.length ? <div className="cart-items">{cart.map((item) => <article className="cart-item" key={item.id}><img src={item.imageUrl} alt={item.name} onError={showFallback}/><div className="cart-item-info"><h3>{item.name}</h3><p>{item.note}</p><strong>{money(item.price)}</strong><div className="quantity-control"><button onClick={() => onQuantity(item.id, -1)} aria-label={`Remove one ${item.name}`}>−</button><span>{item.quantity}</span><button onClick={() => onQuantity(item.id, 1)} aria-label={`Add one ${item.name}`}>+</button></div></div><button className="remove-item" onClick={() => onRemove(item.id)}>Remove</button></article>)}</div> : <div className="empty-cart"><span>♡</span><p>Your bag is waiting for something lovely.</p><button className="text-link" onClick={onBack}>Find a gift ↗</button></div>}
      </div>
      <form className="checkout-panel customer-form" onSubmit={(event) => { event.preventDefault(); onPlaceOrder() }}><div className="panel-title"><h2>Where should we send the love?</h2><span>Delivery details</span></div><div className="form-grid"><label>Full name<input required autoComplete="name" value={customer.name} onChange={(e) => onCustomer('name', e.target.value)} placeholder="Your name"/></label><label>Email address<input type="email" required autoComplete="email" value={customer.email} onChange={(e) => onCustomer('email', e.target.value)} placeholder="you@example.com"/></label><label className="wide-field">Street address<input required autoComplete="street-address" value={customer.address} onChange={(e) => onCustomer('address', e.target.value)} placeholder="Street and number"/></label><label>City<input required autoComplete="address-level2" value={customer.city} onChange={(e) => onCustomer('city', e.target.value)} placeholder="City"/></label><label>ZIP / postal code<input required autoComplete="postal-code" value={customer.postal} onChange={(e) => onCustomer('postal', e.target.value)} placeholder="ZIP code"/></label><label className="wide-field">Gift note <span className="optional-label">Optional</span><textarea value={customer.note} onChange={(e) => onCustomer('note', e.target.value)} placeholder="Write a little something from you…" rows="3"/></label></div><p className="privacy-note">Your details are saved only in this browser for this local shopping experience.</p>
      </form>
    </div><aside className="order-summary"><span className="eyebrow">THE LITTLE DETAILS</span><h2>Order summary</h2><div className="summary-row"><span>Gifts subtotal</span><span>{money(subtotal)}</span></div><div className="summary-row"><span>Delivery</span><span>{shipping === 0 ? 'On us' : money(shipping)}</span></div>{subtotal > 0 && subtotal < 75 && <p className="shipping-hint">You’re ${ (75 - subtotal).toFixed(2) } away from free delivery.</p>}<div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div><button className="place-order" disabled={!cart.length} onClick={() => document.querySelector('.customer-form')?.requestSubmit()}>Place your order <span>↗</span></button><p className="checkout-disclaimer">Local checkout only · No payment is collected</p><div className="summary-foot">♡ &nbsp; Packed with care, always</div></aside></div>
  </section>
}
